### ISSUE TITLE
Failed to inject image/module.

### ISSUE THREAD

**Issue by Umbrozium** [rei-kes/Amalgam#1]
Can't say what exactly is the problem, but cheat injection initially takes some time, after which injector returns one of several errors shown below.

![image](https://github.com/rei-kes/Amalgam/assets/38528831/c4223f0f-8334-49a2-8b59-57a3f5d7cf4d)
This is an error from X-Project (updated/modified Xenos) while using "Manual Map" method, which caused the game to crash. Basically translates to "The specified image file did not have the correct format: it did not have an initial MZ."
![image](https://github.com/rei-kes/Amalgam/assets/38528831/f15f383b-f642-4e41-ae7a-79fe8986be66)
The error printed on "Standard Injection" method: "The program can't start because %hs is missing from your computer. Try reinstalling the program to fix the problem."

![image](https://github.com/rei-kes/Amalgam/assets/38528831/86f5c63e-7dff-44a0-81a1-7f5b58db4268)
I got this error on Extreme Injector while using "Standard Injection" method.
"Manual Map" returns successful injection, but crashes the game.

Xenos errors are not included as they are not informative enough, besides printing "Failed to inject image" followed by the same 2 error codes provided by X-Project.

**Comment by rei-kes** [comment]
did you get the dll through the actions tab

**Comment by Gergish001** [comment]
ok ExIn work to me but at least we all need 1 injector that works for everyone

**Comment by Umbrozium** [comment]
> did you get the dll through the actions tab

Yes, I did. The debug one is given to me by SalmonDev but the results of the debug and the build from actions is the same.

**Comment by Umbrozium** [comment]
> ok ExIn work to me but at least we all need 1 injector that works for everyone

It's not an injector issue. It's missing or corrupted dependencies issue most likely.

**Comment by Gergish001** [comment]
> > ok ExIn work to me but at least we all need 1 injector that works for everyone
> 
> It's not an injector issue. It's missing or corrupted dependencies issue most likely.

dont have a problem here to it

**Comment by Umbrozium** [comment]
@rei-kes Can you tell me what information I need to provide to pinpoint what the issue is?

**Comment by Umbrozium** [comment]
UPDATE: The issue might be the fact that the DLL is incompatible in terms of instructions with my CPU, which only supports AVX, and not AVX2. This is something I didn't know would be the case initially, as I assumed the DLL is built on the older AVX instructions. I guess my only suggestion would be to make an additional AVX built version?

**Comment by progamienr** [comment]
^^

**Comment by Umbrozium** [comment]
I tried the AVX DLL and it worked so I am going to close the issue. However I hope the further releases will include AVX builds as well, if possible.
