### ISSUE TITLE
Which injector is recommended?

### ISSUE THREAD

**Issue by rjdXpxigYxNT** [rei-kes/Amalgam#10]

**Comment by phonkv2** [comment]
any 64 bit injector

**Comment by Reycko** [comment]
I recommend Xenos with VAC-Bypass-Loader

**Comment by Gergish001** [comment]
extreme injector works to me [Vac bypass](https://github.com/danielkrupinski/VAC-Bypass)

**Comment by rei-kes** [comment]
i personally recommend xenos, though i have heard some other injectors work fine. i use daniel krupinski's vac bypass and it hasn't given me any issues.
