### ISSUE TITLE
Add jitter antiaim modes from fed:main

### ISSUE THREAD

**Issue by Rayhangege** [rei-kes/Amalgam#11]
Please add all jitter anti aim modes including invert and all antiaim modes from fed:main that didnt exist on amalgam/reifware

**Comment by SamlonDev** [comment]
paste it yourself

**Comment by Rayhangege** [comment]
no

**Comment by SamlonDev** [comment]
then use main fed and shatap

**Comment by Rayhangege** [comment]
no ur a fish so shutup

**Comment by SamlonDev** [comment]
you're talking to the guy who pasted followbot to reifork, please shatap and go use proto.tf or bigpackets

**Comment by Rayhangege** [comment]
who uses followbottik

**Comment by SamlonDev** [comment]
you gotta cope with not having followbotik somehow

**Comment by progamienr** [comment]
can you guys shut the fuck up

**Comment by SamlonDev** [comment]
shut up, I am HvHing right now

**Comment by progamienr** [comment]
-rep noob hvhee

**Comment by SamlonDev** [comment]
[SalmonPaste] **programienr** has the tag **retard**

**Comment by pay2lose2** [comment]
if you care enough, you can actually use spin to mimic some of the missing modes
setting spin speed (click on the value and then type number) to 45 makes it jitter from one site to another and so on, just play around and see what seems to be the best for you. if it's off then use offset to align it properly

there's no proper way to do it with pitch, maybe at most having 2 binds and a macro in background but other than that, probably not

hope it helps
