### ISSUE TITLE
feature request(s): Triggerbot, Visuals "Team Medics" target.

### ISSUE THREAD

**Issue by Reycko** [rei-kes/Amalgam#12]
1. Triggerbot:
> - A triggerbot that automatically shoots when the crosshair is aiming at the target.
> - Can select certain targets to aim at.

> Options:

> - "Only Headshots": Triggerbot only works if aiming at the head. Sniper only.
> - "Wait for Charge": Triggerbot only shoots if there is enough charge to one-shot. Sniper only.
> - "Point Scale": Works just like Aimbot's point scale option.

> - Auto Backstab & Auto Airblast could be moved there.

2. Visuals: Show Team Medics
> - Similar to the feature in SEOwned(DE), where Visuals can apply to the team medics only.

**Comment by SamlonDev** [comment]
może jeszcze frytki do tego

**Comment by phonkv2** [comment]
> 1. Triggerbot:
> 
> > - A triggerbot that automatically shoots when the crosshair is aiming at the target.
> 
> > - Can select certain targets to aim at.
> 
> 
> 
> > Options:
> 
> 
> 
> > - "Only Headshots": Triggerbot only works if aiming at the head. Sniper only.
> 
> > - "Wait for Charge": Triggerbot only shoots if there is enough charge to one-shot. Sniper only.
> 
> > - "Point Scale": Works just like Aimbot's point scale option.
> 
> 
> 
> > - Auto Backstab & Auto Airblast could be moved there.
> 
> 
> 
> 2. Label Selection
> 
> > - A feature that lets you select labels in Targets. Can be useful for targetting someone even then they aren't in the targets.
> 
> Example: Label "Friend" -> Show ESP for them
> 
> > - Perhaps a way to disable someone from getting targeted if they have the label, even when they aren't in the targets
> 
> > This might already be a feature, I did not really mess with labels that much yet
> 
> 
> 
> 3. Visuals: Show Team Medics
> 
> > - Similar to the feature in SEOwned(DE), where Visuals can apply to the team medics only.

Label section exists for esp you can set friend esp priority esp etc it exists just remember to enable the esp from the main esp tab with the drop down

Automations tab aka triggerbot is probably being rewritten by rei as far as i know

Not sure why you would need something like show team medics
if your friend is playing medic they can simply appear on the friend esp i see no use to this

**Comment by Reycko** [comment]
> > 1. Triggerbot:
> > 
> > > * A triggerbot that automatically shoots when the crosshair is aiming at the target.
> > 
> > 
> > > * Can select certain targets to aim at.
> > 
> > 
> > > Options:
> > 
> > 
> > > * "Only Headshots": Triggerbot only works if aiming at the head. Sniper only.
> > 
> > 
> > > * "Wait for Charge": Triggerbot only shoots if there is enough charge to one-shot. Sniper only.
> > 
> > 
> > > * "Point Scale": Works just like Aimbot's point scale option.
> > 
> > 
> > > * Auto Backstab & Auto Airblast could be moved there.
> > 
> > 
> > 
> > 2. Label Selection
> > 
> > > * A feature that lets you select labels in Targets. Can be useful for targetting someone even then they aren't in the targets.
> > 
> > 
> > Example: Label "Friend" -> Show ESP for them
> > > * Perhaps a way to disable someone from getting targeted if they have the label, even when they aren't in the targets
> > 
> > 
> > > This might already be a feature, I did not really mess with labels that much yet
> > 
> > 
> > 
> > 3. Visuals: Show Team Medics
> > 
> > > * Similar to the feature in SEOwned(DE), where Visuals can apply to the team medics only.
> 
> Label section exists for esp you can set friend esp priority esp etc it exists just remember to enable the esp from the main esp tab with the drop down
> 
> Automations tab aka triggerbot is probably being rewritten by rei as far as i know
> 
> Not sure why you would need something like show team medics if your friend is playing medic they can simply appear on the friend esp i see no use to this

I only enable ESP for enemies and would like to see info like Uber and Health through the ESP, without having to manually add every medic to a label.

**Comment by phonkv2** [comment]
> > > 1. Triggerbot:
> 
> > > 
> 
> > > > * A triggerbot that automatically shoots when the crosshair is aiming at the target.
> 
> > > 
> 
> > > 
> 
> > > > * Can select certain targets to aim at.
> 
> > > 
> 
> > > 
> 
> > > > Options:
> 
> > > 
> 
> > > 
> 
> > > > * "Only Headshots": Triggerbot only works if aiming at the head. Sniper only.
> 
> > > 
> 
> > > 
> 
> > > > * "Wait for Charge": Triggerbot only shoots if there is enough charge to one-shot. Sniper only.
> 
> > > 
> 
> > > 
> 
> > > > * "Point Scale": Works just like Aimbot's point scale option.
> 
> > > 
> 
> > > 
> 
> > > > * Auto Backstab & Auto Airblast could be moved there.
> 
> > > 
> 
> > > 
> 
> > > 
> 
> > > 2. Label Selection
> 
> > > 
> 
> > > > * A feature that lets you select labels in Targets. Can be useful for targetting someone even then they aren't in the targets.
> 
> > > 
> 
> > > 
> 
> > > Example: Label "Friend" -> Show ESP for them
> 
> > > > * Perhaps a way to disable someone from getting targeted if they have the label, even when they aren't in the targets
> 
> > > 
> 
> > > 
> 
> > > > This might already be a feature, I did not really mess with labels that much yet
> 
> > > 
> 
> > > 
> 
> > > 
> 
> > > 3. Visuals: Show Team Medics
> 
> > > 
> 
> > > > * Similar to the feature in SEOwned(DE), where Visuals can apply to the team medics only.
> 
> > 
> 
> > Label section exists for esp you can set friend esp priority esp etc it exists just remember to enable the esp from the main esp tab with the drop down
> 
> > 
> 
> > Automations tab aka triggerbot is probably being rewritten by rei as far as i know
> 
> > 
> 
> > Not sure why you would need something like show team medics if your friend is playing medic they can simply appear on the friend esp i see no use to this
> 
> 
> 
> I only enable ESP for enemies and would like to see info like Uber and Health through the ESP, without having to manually add every medic to a label.

Thats upto rei but it is a useless feature imo

**Comment by rei-kes** [comment]
triggerbot is already a thing if you use smooth aim with 100% smoothing. as for team medics, that is not planned for the time being.
