### ISSUE TITLE
Chat won't open (F2P)

### ISSUE THREAD

**Issue by mcTusa** [rei-kes/Amalgam#17]
**Description of the issue:**
  Chat won't open when you are F2P, even using your x32 Fedoraware fork it works on x32.
  **Config used:**
  I think this don't matter.
  **Steps to reproduce said issue:**
  Try to open chat.

**Comment by phonkv2** [comment]
you cant chat as a f2p you have to spend 5$ to be able to talk

**Comment by mcTusa** [comment]
yea but i can't even open party chat in-game (only while in main menu). If i'm using Fedoraware fork from rei-kes (x32) i can open party chat.

**Comment by phonkv2** [comment]
hmm try changing the keybind for the party chat default is p

**Comment by mcTusa** [comment]
already have backspace lol

**Comment by mcTusa** [comment]
Yeah, still cannot open chat. Sad.

**Comment by phonkv2** [comment]
rip cant really help just buy some cheap shit in tf2 mann co store so you can talk

**Comment by Pandoroeo** [comment]
Use mastercomfig (Details below). Mastercomfig has an option to enable chat. This does NOT bypass f2p restrictions, it simply enables chat. (You could have disabled chat by accident.) Go to https://docs.comfig.app/latest/setup/install/ for a tutorial. Use mastercomfig _MEDIUM HIGH_. It provides a balance of visuals and preformance. Lower presets, such as medium, also **break** chams.

**Comment by rei-kes** [comment]
there were a couple hooks that i didn't port over as i wasn't sure what use they had, and one of them may have been this. i may add this back in in the future, though in the mean time is it possible to use the party chat in the hud?

**Comment by mcTusa** [comment]
> there were a couple hooks that i didn't port over as i wasn't sure what use they had, and one of them may have been this. i may add this back in in the future, though in the mean time is it possible to use the party chat in the hud?

Yeah, I can use party chat in hud.

I will close issue then.
