### ISSUE TITLE
Cheat Doesnt Open

### ISSUE THREAD

**Issue by Cheesepzi** [rei-kes/Amalgam#18]
I inject the cheat and nothing happens when i try to press insert nothing happened 
  config used: none (obvious)

**Comment by Cheesepzi** [comment]
i tried injecting avx too didnt work

**Comment by canedoly** [comment]
do you have "Amalgam injected" in the console?

**Comment by Cheesepzi** [comment]
i injectd it but i dont see it in the console

**Comment by canedoly** [comment]
skill issue ngl

**Comment by Cheesepzi** [comment]
ok ill go play legit then
