### ISSUE TITLE
Just a question to rei

### ISSUE THREAD

**Issue by Gergish001** [rei-kes/Amalgam#19]
Do you going to do a new injector to use amalgam with vac-bypass like a original fedoraloader but w/o issues of injecting on various machines?

**Comment by baubaubayb** [comment]
just use tfghost its updated for 64x

**Comment by Gergish001** [comment]
> just use tfghost its updated for 64x

nuh tf2ghost is fucked up on my machine

**Comment by RandomTNT** [comment]
bro start tfghost v2
it injects the vacbypass
close tfghost
inject with good o' xenos

**Comment by Gergish001** [comment]
> bro start tfghost v2 it injects the vacbypass close tfghost inject with good o' xenos

in my past experience tf2ghost just give me vac cuz "VAC bypass is failed" i dont trust to it anymore
Xenos also dont work to me well, only ExIn work properly with auto-inject, before it i use vac bypass from fed-loader cuz it works but i dont want to use 2 injectors i just need 1 that works for me (maybe other users)
