### ISSUE TITLE
Make the cheat pastable again

### ISSUE THREAD

**Issue by SamlonDev** [rei-kes/Amalgam#2]
aka. revert reileykun changes, or at least make a branch without them, they are very yucky and they change a lot of code

**Comment by phonkv2** [comment]
> aka. revert reileykun changes, or at least make a branch without them, they are very yucky and they change a lot of code

no get good

**Comment by rei-kes** [comment]
what the fuck are you even talking about

**Comment by phonkv2** [comment]
owned bottik
