### ISSUE TITLE
Keybinds "Conditions"

### ISSUE THREAD

**Issue by XenoxUSser** [rei-kes/Amalgam#23]
no matter how much i try to set them up it does not seem to function
I set the name
then the parent like Force crits
it does not let me save the condition afterwards only if i leave parent empty

**Comment by veteneso** [comment]
you dont set the parent
you set a condition without parent, then change the condition with the pencil button

**Comment by XenoxUSser** [comment]
> you dont set the parent you set a condition without parent, then change the condition with the pencil button

i tried but either way it does not let me set a parent whatever i try

**Comment by veteneso** [comment]
dude the parent is not needed idk what ur thinking process is

**Comment by XenoxUSser** [comment]
what is the parent for then tho

**Comment by veteneso** [comment]
i do not know but its not needed

**Comment by XenoxUSser** [comment]
ok figured it out now one unusual way to configure keybinds but unique i guess

**Comment by phonkv2** [comment]
> ok figured it out now one unusual way to configure keybinds but unique i guess

https://github.com/rei-kes/Fedoraware/issues/20
