### ISSUE TITLE
Melee 180 degreese

### ISSUE THREAD

**Issue by XenoxUSser** [rei-kes/Amalgam#26]
is there a way to make it so melee aimbot is 180 degrees but not the actual aimbot? kinda annoying that the aimbot uses the fov for everything

**Comment by phonkv2** [comment]
condition>weapon type > meele set the fov to 180

**Comment by XenoxUSser** [comment]
> condition>weapon type > meele set the fov to 180

ah okay thanks one other thing does melee use backtrack ticks cause ive been inside backtrack ticks and melee didnt swing at them
