### ISSUE TITLE
Chams are bugging out shortly even after fixing them

### ISSUE THREAD

**Issue by XenoxUSser** [rei-kes/Amalgam#30]
im only using chams for backtrack they just start glitching out when i press fix chams it stays a few seconds then glitch out again

the second pic is the red scouts backtrack chams

![image](https://github.com/rei-kes/Amalgam/assets/33065711/a1faf972-34d7-4ff6-94e3-31b9742585a5)

![image](https://github.com/rei-kes/Amalgam/assets/33065711/f734ae54-8a75-49e7-ab04-428d6e7bddc2)

**Comment by XenoxUSser** [comment]
sorry for the low qualy recorded them as clips in 720p

**Comment by Gergish001** [comment]
> sorry for the low qualy recorded them as clips in 720p

use this launch options -dxlevel 98 -windowed -noborder -novid and dont have any issue after

**Comment by Gergish001** [comment]
and its a bug from alt-tab causes a chams bounded at center of the map

**Comment by XenoxUSser** [comment]
> > sorry for the low qualy recorded them as clips in 720p
> 
> use this launch options -dxlevel 98 -windowed -noborder -novid and dont have any issue after

nah turned my nvidia up to 1080 p now

**Comment by XenoxUSser** [comment]
> and its a bug from alt-tab causes a chams bounded at center of the map

i also noticed that alt tabbing with menu open moves every single menu item to one point having to remove everything into place or use load config

**Comment by XenoxUSser** [comment]
> and its a bug from alt-tab causes a chams bounded at center of the map

is there a way to fix it or no

**Comment by XenoxUSser** [comment]
did your launch option thingie lets hope that fixes it

**Comment by Gergish001** [comment]
> did your launch option thingie lets hope that fixes it

it fix for me

**Comment by RileyKun** [comment]
DME moment

**Comment by XenoxUSser** [comment]
seems to have fixed it same with the menu thing thanks lads
