### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by Rayhangege** [rei-kes/Amalgam#4]
Note:My computer is compatible for AVX2

1. Sometimes game crashes when firing a projectile with aimbot autoshoot (last time it happened it was with huntsman)
2. Game crashed at a random time with an error saying created minidump minidump saved in desktop

**Comment by phonkv2** [comment]
> Note:My computer is compatible for AVX2
> 
> 
> 
> 1. Sometimes game crashes when firing a projectile with aimbot autoshoot (last time it happened it was with huntsman)
> 
> 2. Game crashed at a random time with an error saying created minidump minidump saved in desktop

crash might be related to vac bypass (cuz it happened to me to not while shooting just after playing for a while)
