### ISSUE TITLE
dt and crit bars

### ISSUE THREAD

**Issue by Tremzy** [rei-kes/Amalgam#7]
how do i show the dt and crit bars on screen?

**Comment by pay2lose2** [comment]
tremzy for fuck sake, it's in visuals > menu > indicators

**Comment by Tremzy** [comment]
bro its so bad menu alignment

**Comment by SamlonDev** [comment]
then change it, the cheat is open source

**Comment by phonkv2** [comment]
> bro its so bad menu alignment

user issue

**Comment by Tremzy** [comment]
cheat issue

**Comment by pay2lose2** [comment]
> cheat issue

i agree with phonk, it's your skill issue. sorry bud

**Comment by Tremzy** [comment]
bros so mad

**Comment by phonkv2** [comment]
> bros so mad

dont use the cheat
thanks

**Comment by Gergish001** [comment]
> > bros so mad
> 
> dont use the cheat thanks

true

**Comment by Tremzy** [comment]
bro you got mad over a question

**Comment by Tremzy** [comment]
autist...

**Comment by wattome** [comment]
tremzy you could've figured it out on your own if you had a brain and simple common sense. Or just don't use any cheat at all lol

**Comment by Tremzy** [comment]
bad menu design and placement + this guy got mad over a simple question

**Comment by essentialsasset** [comment]
tremzy is the guy who reuploaded cheats with malware, do not talk with him.

**Comment by pay2lose2** [comment]
> tremzy is the guy who reuploaded cheats with malware, do not talk with him.

wouldn't say with malware, but he's quite retarded for sure

**Comment by Tremzy** [comment]
it seems like youre out of arguments...

**Comment by pay2lose2** [comment]
> it seems like youre out of arguments...

my brother in christ you coped about menu placement that would not be an issue if you weren't this retarded and actually paid attention to menu for atleast 5 seconds (stop watching skibidi toilet please). my point stands correctly.

**Comment by moneymouth321** [comment]
> > it seems like youre out of arguments...
> 
> my brother in christ you coped about menu placement that would not be an issue if you weren't this retarded and actually paid attention to menu for atleast 5 seconds (stop watching skibidi toilet please). my point stands correctly.

noob

**Comment by Tremzy** [comment]
are you speaking to yourself or what?
