### ISSUE TITLE
Nospread doesn't work

### ISSUE THREAD

**Issue by Rayhangege** [rei-kes/Amalgam#9]
So i turned on nospread and used the minigun it didnt work and the bullet still spreads, the server already has a uptime of 9 days and 16 hours, Thats already 232, i rlly want this cheat to be able to compete with rijin and other paid cheats with features like auto vacc near threat, anti aim near threat and all "threat" features that exist in rijin and mb,i know this is a free and a forked cheat but if you can make it compete with rijin we all will be super happy

**Comment by TwoTrickLikesKids** [comment]
So i turned on nospread and used the minigun it didnt work and the bullet still spreads, the server already has a uptime of 9 days and 16 hours, Thats already 232, i rlly want this cheat to be able to compete with rijin and other paid cheats with features like auto vacc near threat, anti aim near threat and all "threat" features that exist in rijin and mb,i know this is a free and a forked cheat but if you can make it compete with rijin we all will be super happy

**Comment by moneymouth321** [comment]
So i turned on nospread and used the minigun it didnt work and the bullet still spreads, the server already has a uptime of 9 days and 16 hours, Thats already 232, i rlly want this cheat to be able to compete with rijin and other paid cheats with features like auto vacc near threat, anti aim near threat and all "threat" features that exist in rijin and mb,i know this is a free and a forked cheat but if you can make it compete with rijin we all will be super happy

**Comment by SamlonDev** [comment]
So i turned on nospread and used the minigun it didnt work and the bullet still spreads, the server already has a uptime of 9 days and 16 hours, Thats already 232, i rlly want this cheat to be able to compete with rijin and other paid cheats with features like auto vacc near threat, anti aim near threat and all "threat" features that exist in rijin and mb,i know this is a free and a forked cheat but if you can make it compete with rijin we all will be super happy

**Comment by pronery** [comment]
Niger minigus work like a shotgun except it shoots continuously. How do you expect to nospread a shotgun?

**Comment by Niximkk** [comment]
Minigus
![images (1)](https://github.com/rei-kes/Amalgam/assets/85513545/a5e15eda-09df-4149-b0c2-9c231a205577)

**Comment by pronery** [comment]
> Minigus ![images (1)](https://private-user-images.githubusercontent.com/85513545/335575252-a5e15eda-09df-4149-b0c2-9c231a205577.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDY1NjksIm5iZiI6MTcxNzI0NjI2OSwicGF0aCI6Ii84NTUxMzU0NS8zMzU1NzUyNTItYTVlMTVlZGEtMDlkZi00MTQ5LWIwYzItOWMyMzFhMjA1NTc3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjUxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWRlZWQ1Mzc0MzJmYTdkZGNjOTRjYmNlZDQ2MmVmNTkyNDMwOTE3ZjZkZGM0MWFhY2EwMDIzZWNkNGZlN2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OzS0L7254skaWVOKyT2SIUYaVYxsU8jS0qwXOT1NKmU)

stfu
